### ISSUE TITLE
Data distribution

### ISSUE THREAD

**Issue by RainbowRevenge** [uds-lsv/human#10]
There is a bug, where while an annotator is working on an annotation, other annotators could get the same annotation as well, circumventing the max_annotations setting.

Solution:
1. Save the current annotation of each user in the user table in the database.
2. Remove the current annotation when the finished annotation is written to the db
3. If there is a current annotation and the client requests a new one, send the current one again.

**Comment by GeetDsa** [comment]
@RainbowRevenge, I am not 100% sure, but I think I had seen this in the code running on the server and corrected in the server itself. I think I can have a look at this, but need a little time.

**Comment by RainbowRevenge** [comment]
@GeetDsa It's fine, @vdrummer has a pull request almost ready.

**Comment by RainbowRevenge** [comment]
@GeetDsa But thanks :)
